name: build-jar

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Maven package
        working-directory: ./rabbitmq
        run: mvn package

      - name: Upload jar
        uses: actions/upload-artifact@v2.2.2
        working-directory: ./rabbitmq
        with:
          name: rabbitmq-java-spring-jar
          path: target/*.jar